---
- hosts: localhost
  connection: local
  tasks:
    - debug: 
        msg: The word is {{ ansible_word_2 }}
    - set_stats:
        data:
          variable_transfered_is: "{{ ansible_word_2 }}"
